# localization.py

locales = {
    'ru': {
        # --- Старт ---
        "select_language": "Выберите язык / Select your language:",
        "welcome": "Привет, {mention}! Я бот для создания интерактивных диаграмм.\n\nОтправь мне **текст** или **фото**, чтобы создать первый блок.",
        
        # --- Главное меню и кнопки ---
        "editing_diagram": "📝 Редактируем: **{name}**\n{message}\n",
        "diagram_is_empty": "Диаграмма пуста. Отправьте текст или фото, чтобы создать первый блок.",
        "current_nodes": "Текущие блоки:\n",
        "add_edge_to_see_preview": "\nДобавьте связь (↔️ Связать), чтобы увидеть превью.",
        "stats_line": "Блоков: {nodes} | Связей: {edges}",
        "btn_add_node": "➕ Блок", "btn_manage_nodes": "✏️ Блоки",
        "btn_add_edge": "↔️ Связать", "btn_manage_edges": "🔗 Связи",
        "btn_diagrams": "💾 Диаграммы", "btn_settings": "⚙️ Настройки",
        "btn_download_png": "📥 Скачать PNG",
        
        # --- Сообщения об успехе/ошибке ---
        "node_added_text": "✅ Блок «{text}» добавлен!",
        "node_added_image": "✅ Блок с изображением добавлен!",
        "node_deleted": "✅ Блок удален.",
        "node_edited": "✅ Блок изменен.",
        "edge_added": "✅ Связь добавлена.",
        "edge_deleted": "✅ Связь удалена.",
        "theme_changed": "🎨 Тема изменена.",
        "diagram_saved": "✅ Диаграмма сохранена как «{name}»",
        "diagram_loaded": "📂 Загружена диаграмма «{name}»",
        "diagram_created": "✨ Создана новая пустая диаграмма «{name}»",
        "error_critical_render": "❗️Критическая ошибка рендеринга. Попробуйте изменить диаграмму.",
        "error_no_nodes_to_manage": "❗️ Нет блоков для управления.",
        "error_need_2_nodes": "❗️ Нужно как минимум 2 блока, чтобы создать связь.",
        "error_no_edges_to_manage": "❗️ Нет связей для управления.",
        "error_no_diagrams_saved": "❗️ Нет сохраненных диаграмм.",
        "error_diagram_exists": "❗️ Диаграмма с таким именем уже существует.",
        "error_nothing_to_download": "❗️ Нечего скачивать. Диаграмма пуста или не содержит связей.",
        
        # --- Процессы ---
        "saving_image": "🖼️ Сохраняю изображение...",
        "preparing_file": "Готовлю файл...",
        "prompt_add_node": "Отправьте текст или фото для нового блока.",
        "menu_manage_nodes": "Управление блоками:",
        "btn_back": "◀️ Назад",
        "node_repr_image": "[🖼️ Изображение]",
        "prompt_edit_node": "Отправьте новый текст для блока.",
        "prompt_add_edge_start": "Выберите НАЧАЛЬНЫЙ блок:",
        "prompt_add_edge_end": "Выберите КОНЕЧНЫЙ блок:",
        "menu_manage_edges": "Управление связями:",
        "menu_settings": "Настройки:",
        "menu_themes": "Настройки темы:",
        "btn_dark_theme": "🌙 Тёмная", "btn_light_theme": "☀️ Светлая",
        "menu_diagrams": "Управление диаграммами:",
        "btn_save_current": "💾 Сохранить текущую",
        "btn_load": "📂 Загрузить",
        "btn_create_new": "✨ Создать новую",
        "prompt_save_diagram": "Введите имя для сохранения текущей диаграммы:",
        "prompt_load_diagram": "Выберите диаграмму для загрузки:",
        "btn_lang": "🌐 Язык",
        "menu_lang": "Выберите язык:",
    },
    'en': {
        # --- Start ---
        "select_language": "Select your language / Выберите язык:",
        "welcome": "Hello, {mention}! I'm a bot for creating interactive diagrams.\n\nSend me **text** or a **photo** to create the first block.",
        
        # --- Main Menu & Buttons ---
        "editing_diagram": "📝 Editing: **{name}**\n{message}\n",
        "diagram_is_empty": "Diagram is empty. Send text or a photo to create the first block.",
        "current_nodes": "Current blocks:\n",
        "add_edge_to_see_preview": "\nAdd a connection (↔️ Connect) to see a preview.",
        "stats_line": "Nodes: {nodes} | Edges: {edges}",
        "btn_add_node": "➕ Node", "btn_manage_nodes": "✏️ Nodes",
        "btn_add_edge": "↔️ Connect", "btn_manage_edges": "🔗 Edges",
        "btn_diagrams": "💾 Diagrams", "btn_settings": "⚙️ Settings",
        "btn_download_png": "📥 Download PNG",
        
        # --- Success/Error Messages ---
        "node_added_text": "✅ Node «{text}» added!",
        "node_added_image": "✅ Image node added!",
        "node_deleted": "✅ Node deleted.",
        "node_edited": "✅ Node updated.",
        "edge_added": "✅ Edge added.",
        "edge_deleted": "✅ Edge deleted.",
        "theme_changed": "🎨 Theme changed.",
        "diagram_saved": "✅ Diagram saved as «{name}»",
        "diagram_loaded": "📂 Loaded diagram «{name}»",
        "diagram_created": "✨ Created a new empty diagram «{name}»",
        "error_critical_render": "❗️Critical rendering error. Please try changing the diagram.",
        "error_no_nodes_to_manage": "❗️ No nodes to manage.",
        "error_need_2_nodes": "❗️ You need at least 2 nodes to create an edge.",
        "error_no_edges_to_manage": "❗️ No edges to manage.",
        "error_no_diagrams_saved": "❗️ No saved diagrams.",
        "error_diagram_exists": "❗️ A diagram with this name already exists.",
        "error_nothing_to_download": "❗️ Nothing to download. The diagram is empty or has no edges.",
        
        # --- Processes ---
        "saving_image": "🖼️ Saving image...",
        "preparing_file": "Preparing file...",
        "prompt_add_node": "Send text or a photo for the new node.",
        "menu_manage_nodes": "Manage nodes:",
        "btn_back": "◀️ Back",
        "node_repr_image": "[🖼️ Image]",
        "prompt_edit_node": "Send the new text for the node.",
        "prompt_add_edge_start": "Select the START node:",
        "prompt_add_edge_end": "Select the END node:",
        "menu_manage_edges": "Manage edges:",
        "menu_settings": "Settings:",
        "menu_themes": "Theme settings:",
        "btn_dark_theme": "🌙 Dark", "btn_light_theme": "☀️ Light",
        "menu_diagrams": "Manage diagrams:",
        "btn_save_current": "💾 Save current",
        "btn_load": "📂 Load",
        "btn_create_new": "✨ Create new",
        "prompt_save_diagram": "Enter a name to save the current diagram:",
        "prompt_load_diagram": "Select a diagram to load:",
        "btn_lang": "🌐 Language",
        "menu_lang": "Select language:",
    }
}